[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.142"
redpitaya = "0.31.0"
rp-sys = "0.28.1"

[lib]
crate-type = ['cdylib']
